import { DesignMeta } from '../../../shared/models';

export const RATE_LIMITER_META: DesignMeta = {
  slug: 'rate-limiter',
  title: 'Design a Rate Limiter',
  tagline:
    'A distributed rate limiter protecting APIs using token bucket and sliding window algorithms.',
  section: 'system-design',
  category: 'Infrastructure',
  tags: [
    'algorithms',
    'distributed',
    'api-gateway',
    'throttling',
    'token-bucket',
    'sliding-window',
    'redis',
    'atomicity',
  ],
  technologies: ['Redis', 'Lua', 'Envoy', 'NGINX', 'Token Bucket', 'Sliding Window'],
  difficulty: 'advanced',
  readingTimeMin: 22,
  status: 'published',
  keywords: [
    'throttling',
    'token bucket',
    'leaky bucket',
    'fixed window',
    'sliding window log',
    'sliding window counter',
    'quota',
    'distributed rate limiting',
    'atomic counter',
    'redis lua',
    '429',
    'fail open',
    'api gateway',
    'tiered limits',
  ],
  dateAdded: '2026-06-28',
  popularity: 82,
  icon: 'RL',
  heroGradient: 'linear-gradient(135deg, #0891b2 0%, #164e63 100%)',
};
