import { DesignMeta } from '../../../shared/models';

export const NOTIFICATION_SYSTEM_META: DesignMeta = {
  slug: 'notification-system',
  title: 'Design a Notification System',
  tagline:
    'A multi-channel notification service delivering push, SMS, and email at scale with deduplication.',
  section: 'system-design',
  category: 'Infrastructure',
  tags: [
    'messaging',
    'fan-out',
    'queues',
    'multi-channel',
    'idempotency',
    'rate-limiting',
    'retries',
    'preferences',
  ],
  technologies: ['Kafka', 'Redis', 'APNs', 'FCM', 'SES', 'Twilio', 'Cassandra'],
  difficulty: 'advanced',
  readingTimeMin: 23,
  status: 'published',
  keywords: [
    'push notifications',
    'sms',
    'email',
    'in-app',
    'fan-out',
    'idempotency',
    'deduplication',
    'rate limiting',
    'token bucket',
    'dead letter queue',
    'retries',
    'circuit breaker',
    'user preferences',
    'quiet hours',
    'templating',
  ],
  dateAdded: '2026-06-28',
  popularity: 80,
  icon: 'NS',
  heroGradient: 'linear-gradient(135deg, #7c3aed 0%, #312e81 100%)',
};
